name: Cargo Publish Package

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-new-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Cargo Release and Bump version
      run: |
        git config --global user.email "HideyoshiNakazone@users.noreply.github.com"
        git config --global user.name "HideyoshiNakazone"
        cargo install cargo-bump
        cargo bump patch --git-tag
        git push --tags
    - uses: actions/checkout@v3
    - uses: katyo/publish-crates@v2
      name: Publish
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        dry-run: true
