name: Cargo Publish Package

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Install Cargo Release
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-release
    - name: Bump version
      uses: actions-rs/cargo@v1
      with:
        command: bump
        args: patch --git-tag
    - name: Push changes and tags
      run: |
        git push --follow-tags

  publush:
    needs:
      - increment-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: true
