name: Cargo Publish Package

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Config Github
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Login to Cargo Registry
      run: |
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - name: Install Cargo Release
      run: |
        cargo install cargo-release
    - name: Create Release
      run: |
        cargo release patch \
          --verbose \
          --allow-branch HEAD